package commands

import (
	"math/rand"
	"time"
)

func init() {
	rand.Seed(time.Now().UTC().UnixNano())
}

// Type Quotes contains quotes
type Quotes []string

// randomQuote is a method of the QuoteSlice type that returns a random quote.
func (q Quotes) randomQuote() string {
	return q[rand.Intn(len(q))]
}

// Contains all the quotes fom the game
var quotes = Quotes{"There is a place, beneath those ancient ruins, in the moor, that calls out to the boldest among them...",
	"'We are the Flame!', they cry, 'And Darkness fears us!'",
	"They descend, spurred on by fantasies of riches and redemption to lay bare whatever blasphemous abnormality may slumber restlessly in that unholy abyss...",
	"But Darkness is insidious. Terror and Madness can find cracks in the sturdiest of honors, the most resolute of minds...",
	"And below, in that limitless chasm of Chaos, they will realise the truth of it. 'We are not the Flame!', they will cry out, 'We are but moths and we are DOOMED!'",
	"And their screams will echo amidst the pitiless cyclopean stones...",
	"Ruin has come to our family...",
	"You remember our venerable house, opulent and imperial, gazing proudly from its stoic perch above the moor?",
	"I lived all my years in that ancient, rumor-shadowed manor, fattened by decadence and luxury, and yet I began to tire of conventional extravagance.",
	"Singular, unsettling tales suggested the mansion itself was a gateway to some fabulous, unnamable power. With relic and ritual I meant every effort towards the excavation and recovery of those long buried secrets, exhausting what remained of our family fortune on swarthy workmen and sturdy shovels. At last, in the salt-soaked cracks beneath the lowest foundation, we unearthed that damnable portal of antediluvian evil.",
	"Our every step unsettled the ancient earth. Hideous, rotten aggressors assailed us from the shadows. We drew what strength we could from our companionship, but we were in the realm of death and madness! In the end, I alone, fled, laughing and wailing, through those blackened arcades of antiquity, until consciousness failed me...",
	"You remember our venerable house, opulent and imperial? It is a festering abomination! I beg you, return home, claim your birthright, and deliver our family from the ravenous, clutching shadows of the Darkest Dungeon...",
	"You will arrive along the Old Road.",
	"It winds with a troubling, serpent-like, suggestion through the corrupted countryside, leading only, I fear, to evermore tenebrous places.",
	"There is a sickness in the ancient, pitted cobbles of the Old Road, and on its writhing path, you will face viciousness, violence, and, perhaps, other damnably transcendent terrors.",
	"So, steel yourself, and remember, there can be no bravery without madness.",
	"The Old Road will take you to Hell, but in that gaping abyss, we will find our redemption.",
	"Brigands have run of these lands. Keep to the side paths, the hamlet is just ahead.",
	"Dispatch this thug in brutal fashion, that all may hear of your arrival!",
	"Leave nothing unchecked. There is much to be found in forgotten places.",
	"An ambush! Send these vermin a message: The rightful owner has returned, and their kind is no longer welcome!",
	"Welcome home, such as it is. This squalid hamlet, these corrupted lands. They are yours now, and you are bound to them.",
	"Most will end up here, covered in the poisoned earth, awaiting merciful Oblivion.",
	"Women and men, soldiers and outlaws, fools and corpses. All will find their way to us now that the road is clear.",
	"Word is travelling. Ambition is steering in other cities. We can use this.",
	"More arrive foolishly seeking fortune and glory in this domain... Of the damned.",
	"Great heroes can be found even here, in the mud and rain.",
	"The cobwebs have been dusted, the pews set straight. The abbey calls to the faithful.",
	"A little hope, however desperate, is never without worth.",
	"Gilded icons and dogmatic rituals… For some, a tonic against the bloodshed.",
	"A man in a robe, claiming communion with the Divine? Madness...",
	"Fresh kegs, cards and curtained rooms promise solace to the weary and broken alike.",
	"With enough ale, maybe they can be inured against the horrors below.",
	"Strong drink, a game of chance, and companionship… the rush of life.",
	"All-manner of diversion and dalliance await those who cross the threshold with coin in hand.",
	"Make no mistake; we will face ever greater threat – our soldiers must be ready.",
	"Some may fall... but their knowledge lives on.",
	"Every creature has a weakness – the wise hero trains for what he will face.",
	"A strict regimen is paramount if one is to master the brutal arithmetic of combat.",
	"The bellows blasts once again, the forge stands ready to make weapons of war.",
	"A sharper sword, a stronger shield – anything to prolong a soldier’s life.",
	"In the end every plan relies upon a strong arm and tempered steel.",
	"Fan the flames, mould the metal; we are raising an army.",
	"Curious methodologies and apparatus… It calms even the most tormented souls.",
	"Experimental techniques and tonics can overcome things a sharpened sword cannot.",
	"The frontline of this war is not in the dungeon, but rather inside the mind.",
	"Trinkets and charms, gathered from all-the-forgotten-corners of the earth.",
	"Rarity and curios… Sold at a profit, of course.",
	"Idol, amulet or a lucky charm. The simplest object can be the talisman against evil.",
	"An increasing stockpile of curios trinkets… Gathered from forbidden places.",
	"At home in wild places, she is a stalwart survivor and a strict instructor.",
	"Success depends on survival.",
	"They must learn more than brutal blood-letting – they must learn to survive.",
	"Alone in the woods or tunnels, survival is the same. Prepare, persist, and overcome.",
	"In time, you will know the tragic extent of my failings...",
	"The cost of preparedness. Measured, now in gold, later, in blood...",
	"My obsession caused this great foulness, and it is shameful, that I must rely upon you to set it right.",
	"The poor caretaker... I fear his long-standing duties here have affected him.",
	"Once our estate was an envy of this land.",
	"I was lord of this place, before the crows and rats made it their domain.",
	"I remember days, when the sun shone, and laughter could be heard from the tavern.",
	"In truth I cannot tell how much time has passed since I've sent that letter.",
	"Our family name, once so well-regarded, is now barely whispered aloud by decent folk.",
	"I can still see their angry faces, as they stormed the manor... But I was dead before they found me, and the letter was on it's way.",
	"I see something long absent in the sunken faces of passers by, the glimmer of hope.",
	"We dug for months, years, eternity... And we were rewarded with madness...",
	"There is a great horror beneath the manor... A crawling chaos, that must be destroyed!",
	"You answered the letter! Now, like me, you are a part of this place...",
	"Curiosity, interest, obsession... Mile markers on my road to damnation...",
	"Let me share with you terrible wonders I've come to know...",
	"All my life I could feel an insisted gnawing at the back of my mind... It was a yearning, a thirst for discovery, which could be neither numbed, nor sated...",
	"All the decadent horrors I've seen pale in comparison to that final crowning thing... I could not look, nor could I look away...",
	"The plume and the pistol... A pitting end to my folly and a curse upon us all!",
	"Another soul battered and broken, cast aside like a spent torch.",
	"Those without stomach for this place must move on.",
	"Send this one to journey elsewhere, for we have need of sterner stock.",
	"The task ahead is terrible, and weakness cannot be tolerated.",
	"It is done, turn yourself now to the condition of those poor devils, who remain.",
	"Sloped shoulders, wild eyes and a stumbling gate - this one is no more good to us.",
	"Suffer not the lame horse, nor the broken man...",
	"Tortured and reclusive, this man is more dangerous, than he seems.",
	"She searches, where others will not go and sees, what others will not.",
	"Shoot, bandage and pillage. The dancing steps of war.",
	"The thrill of the hunt, the promise of payment.",
	"A mighty sword arm anchored by holy purpose. A zealous warrior.",
	"To those with a keen eye, gold gleams like a dagger's point.",
	"Barbaric rage and unrelenting savagery make for a powerful ally.",
	"Elusive, evasive, persistent. Righteous traits for a rogue.",
	"A lawman and his faithful beast. A bond formed by battle and bloodshed.",
	"He will be laughing still at the end.",
	"This man understands that adversity and existence are one and the same.",
	"The raw strength of youth may be spent, but his eye holds the secrets of a hundred campaigns.",
	"A champion markswoman, keen for a new kind of challenge",
	"To fight the abyss, one must know it.",
	"What better laboratory than the blood-soaked battlefield?",
	"A sister of battle, pious and unrelenting!",
	"The shuffling dead are silenced - we have claimed dominion over the Ruins once more!",
	"Pallid light filters its way through the rotting boughs...let us press on!",
	"The twisting tunnels no longer exhale the toxic stench of degeneracy...",
	"The frothing waters subside; the advantage is ours!",
	"A new enemy - insipid and incurable.",
	"Tonight, the fools make merry. Tomorrow, they die laughing.",
	"The shadows hide the guilty and guilt-ridden alike...",
	"To the resourceful thief, burials are merely... Ephemeral affairs.",
	"Strength, purpose, and peace - all can be found in the focused mind.",
	"Competition fosters skill and confidence...",
	"Seditionists and heretics skulk in the alleys - they must be found out!",
	"The man is slave to the beast, and the beast is slave to the moon.",
	"Behold - righteousness and zealotry - gleaming in the morning sun.",
	"Risk and reward - a siren's call to the enterprising stalker.",
	"Let the organ notes ring out from the Abbey - the Sisters are gathering...",
	"There will be no sleep tonight - the wild shouts and frantic drumming will see to that.",
	"They meet in secret, that none may know the horrifying depths of their inquiries.",
	"Cast out from the 'civilized' world, these men may yet be of use to us.",
	"There is, indeed, no better place for those in search of rarities and forgotten lore...",
	"A ray of sunlight. A beacon of golden hope.",
	"Windows and doors will be bolted. Tonight, something haunts the dark.",
	"A troubling shortage of ale...and a notable absence of good humour.",
	"The beating heart of the gambling hall - now bloodless and still.",
	"Any evidence of excessive exertions must be made scarce. After all, apearances must be maintained...",
	"Ancient and crumbling, the Abbey's masonry fares no better than the faith of its congregation.",
	"Woe to the sheep, for does the absence of the shepherd not invite the wolves?",
	"No amount of scrubbing can remove the stains of such fearsome piety.",
	"Surplus - a rare and wonderful thing!",
	"A modest offering from those few surrounding farms yet untouched by the spreading calamity.",
	"What little there is must suffice, for the time being.",
	"Their customs are curious, and their generosity is notoriously short-lived.",
	"Take advantage of this faith-fueled charity - it will not last.",
	"Death and demise - cause for celebration!",
	"Finally the serum is working, and the side-effects are... manageable.",
	"The preponderance of rare and exotic injuries make this place perfect for the study of suffering.",
	"The town is alive with wild merriment and desperate jubilation!",
	"A fever of wilfull determination sweeps through the barracks!",
	"Let each help the other, and in so doing, help themselves...",
	"An exquisite example of craftsmanship... and futility.",
	"A finely crafted instrument of butchery and bloodshed - yours for the taking.",
	"Even these dirt-covered dullards have their uses - put them to work!",
	"Perhaps things are not as bad as they seem... Muhahahahahahaha",
	"Your soldiers' minds are mired in malignancy - fear has taken root!",
	"Back across the styx - Boatman be damned!",
	"Life... The greatest treasure of all.",
	"No rest, no peace for this wretched soul.",
	"Flames on the horizon, sulfur in the air - the wolves are at the door!",
	"Pace out the halls of your lineage one familiar, now, foreign.",
	"The fiends must be driven back, and what better place to begin, than the seat of our noble line?",
	"There is power in symbols. Collect the scattered scraps of faith and give comfort to the masses.",
	"Can the defiled be consecrated? Can the fallen find rest?",
	"I knew all these paths once, now they are as twisted as my own ambitions",
	"Corruption has soaked the soil, sapping all good life from these groves. Let us burn out this evil.",
	"Our land is remote and unneighbored. Every lost resource must be recovered.",
	"Excise the fungal tumors and the land may yet live.",
	"To prosecute our war against the swine, we must first scout their squalid homes.",
	"They breed quickly down here, in the dark, but perhaps we can slay them even faster.",
	"Even the fiercest beast will lay down when it has not eaten. Steal their food.",
	"The Swine draw power from their horrid markings and crude idols - tear them down!",
	"The smell of rotting fish is almost unbearable",
	"These salt-soaked caverns are teeming with pelagic nightmares. They must be flushed out.",
	"Recover these lost shipments of rarities, that we may prevent",
	"them from falling into even less scrupulous hands...",
	"The flopping, fish-like things abhore the warding sigils. Let us claim this place anew!",
	"The shifted corridors and sloped vaults of our ancestry are beginning to feel familiar.",
	"The great Ruins belong to us, and we will find whatever secrets they hold.",
	"More bones returned to rest. Devils remanded to their abyss.",
	"Room by room, hall by hall, we reclaim what is ours.",
	"Tokens of hope, recovered from the encroaching dark.",
	"The Abbot will be grateful - the trappings of his faith have been restored.",
	"This day belongs to the Light!",
	"Beacons in the darkness, stars in the emptiness of the void.",
	"Every cleared path and charted route reduces the isolation of our troubled estate.",
	"Paths and roads bring soldiers and supplies, let them arrive unharried!",
	"Driving out corruption is an endless battle, but one that must be fought.",
	"The agents of pestilence will yet be driven from our woods!",
	"These medicines will prevent the outbreak of epidemic at our struggling Hamlet.",
	"These tonics and herbs will stave off infection and neutralize contagion",
	"Good fortune and hard work may yet arrest this plague.",
	"Disinfection, at last.",
	"The swinefolk's labyrinth may yet prove to be navigable.",
	"The twisting tunnels seem a little less ...impossible.",
	"Some experiments should have never happened. You are doing just work, ending them.",
	"Their squeals fade, their confidence is shaken!",
	"These foodstuffs yield double benefit: the town may eat, and the Swine will not.",
	"Our supplies are replenished, the soldiers will feast tonight.",
	"Ha ha! Let those dirty beasts worship the mud now!",
	"Robbed of their writings, the Swine will grow ever more ignorant - if such a thing were possible.",
	"Despite its morbid aspect, this twisted, cavernous maze seems almost traversable.",
	"We will find all manner of great and terrible things in this watery tomb...",
	"The pungent odour abates! The things are driven back, for a time.",
	"At last, wholesome marine life can flourish - if indeed there is such a thing.",
	"You will endure this loss and learn from it.",
	"A setback, but not the end of things!",
	"Regroup! Reassemble! Evil is… Timeless, after all.",
	"Wounds to be tended, lessons to be learned.",
	"Failure tests the mettle of heart, brain and body.",
	"You cannot learn a thing you think, you know.",
	"We fall so that we may learn to pick ourselves up once again.",
	"Do not ruminate on this fleeting failure - the campaign is long, and victory will come.",
	"Where there is no peril in the task, there can be no glory in its accomplishment.",
	"Ignorance of your enemy and of yourself will invariably lead to defeat.",
	"Great adversity has a beauty - it is the fire that tempers the blade.",
	"Even the cold stone seems bent on preventing passage...",
	"Nature herself, a victim of the spreading corruption, malformed with misintent.",
	"Such blockages are not surprising. These tunnels predate even the earliest settlers.",
	"Another mariner, another misfortune.",
	"Without tools of iron, you must rely on flesh, an indefatigable purpose...",
	"Curious is the trapmaker's art - his efficacy unwitnessed by his own eyes.",
	"Cruel machinations spring to life, with a singular purpose.",
	"Ancient traps lie in wait, unsprung and thirsting for blood...",
	"Ambushed by foul invention!",
	"Mind, that such misteps are an exception, and not the rule.",
	"Carelessness will find no clemency in this place.",
	"Watch your step.",
	"The light, the promise of safety!",
	"A match is struck, a blazing star is born!",
	"As the light gains purchase, spirits are lifted and purposes made clear.",
	"In radiance may we find victory!",
	"The way is lit, the path is clear. We require only the strength to follow it.",
	"And now, the darkness holds dominion. Black as Death!",
	"The darkness holds much worst than mere trickery… and boogiemen",
	"Darkness closes in, haunting the hearts of men.",
	"Secrets and wonders can be found in the most tenebrous corners of this place.",
	"Terrors may indeed stalk these shadows, but yonder, a glint of gold.",
	"A spark without kindling is a goal without hope.",
	"A moment of respite, a chance to steel oneself against upcoming horrors.",
	"Huddled together, furtive and vulnerable, rats in a maze.",
	"Circle in the dark, the battle may yet be won.",
	"Gathered close in tenuous firelight, an uneasy companionship.",
	"Gnawing hunger sets in, turning the body against itself, weakening the mind…",
	"To fall for such a little thing – a bite of bread.",
	"Packs of steel and war, but nary of thought given to the plough.",
	"No force of will can overcome a failing body.",
	"The requirements of survival cannot be met on an empty stomach.",
	"There can be no hope in this Hell. No hope at all...",
	"Self-preservation is paramount, at any cost.",
	"Those, who covet injury, find it in no short supply.",
	"Frustration and fury, more destructive, than a hundred cannons.",
	"Reeling, gasping, taken over the edge, into Madness!",
	"Fear and frailty finally claim their due...",
	"The walls close in, the shadows whisper of conspiracy!",
	"Anger is power. Unleash it!",
	"A moment of clarity in the eye of the storm.",
	"Many fall in the face of Chaos, but not this one, not today.",
	"A moment of valor shines brightest against the backdrop of despair.",
	"Adversity can foster hope and resilience.",
	"Finding the stuff is only the first test. Now it must be carried home.",
	"Glittering gold, trinkets and baubles. Paid for in blood.",
	"Wealth beyond measure... Awarded to the brave and the foolhardy alike.",
	"If only treasure could staunch the flow of otherworldy corruption...",
	"A handsome reward, for a task well performed.",
	"Forture, waiting to be spent.",
	"Well struck!",
	"A powerful blow!",
	"A singular strike!",
	"A devastating blow!",
	"Masterfully executed!",
	"Impressive!",
	"Precision and power!",
	"A decisive pummeling!",
	"The ground quakes!",
	"Grievous injury, palpable fear...",
	"Death waits for the slightest lapse in concentration.",
	"Dazed, reeling, about to break.",
	"How quickly the tide turns!",
	"Mortality clarified in a single strike!",
	"Such a terrible assault cannot be left unanswered...",
	"Exposed to a killing blow!",
	"Unnerved, unbalanced...",
	"A dizzying blow to body and brain!",
	"Ringing ears, blurred vision... The end approaches...",
	"Confidence surges as the enemy crumbles!",
	"Continue the onslaught! Destroy! Them! ALL!",
	"Their formation is broken! Maintain the offensive!",
	"Press this advantage. Give them no quarter!",
	"As the fiend falls, a faint hope blossoms.",
	"Executed with impunity!",
	"Begone, fiend!",
	"Decimated!",
	"Destroyed!",
	"Obliterated!",
	"Annihilated!",
	"Eradicated!",
	"Another one falls!",
	"Back to the Pit!",
	"Great is the weapon, that cuts on its own!",
	"A slow death, unforseen, unforgiving...",
	"Death by inches...",
	"Slowly, gently, this is how life is taken.",
	"The bigger the beast, the greater the glory.",
	"Their cursed champion falls!",
	"Prodigious size alone does not dissuade the sharpened blade.",
	"Monster's size has no intrinsic merit... Unless, inordinate exsanguination be considered a virtue.",
	"Injury and despondence set the stage for heroism... or cowardice.",
	"A hand's breadth from becoming unwound.",
	"And now the true test: hold fast or expire.",
	"As life ebbs, terrible vistas of emptiness reveal themselves.",
	"Perched at the very precipice of oblivion.",
	"This is no place for the weak or foolhardy.",
	"More blood soaks the soil, feeding the evil therein.",
	"Another life wasted in the pursuit of glory and gold.",
	"More dust, more ashes...more disappointment.",
	"Survival is a tenuous proposition in this sprawling tomb.",
	"These nightmarish creatures can be felled, they can be beaten!",
	"Remind yourself that overconfidence is a slow and insidious killer.",
	"Success, so clearly in view. Or, is it merely a trick of the light?",
	"A trifling victory, but a victory nonetheless.",
	"This expedition, at least, promises success.",
	"As victories mount, so too will resistance.",
	"A victory, perhaps a turning point.",
	"Seize this momentum! Push on, to the task's end!",
	"Be wary, triumphant pride precipitates a dizzying fall.",
	"Foolish horrors! Brought low and driven into the mud!",
	"The sin is not in being outmatched, but in failing to recognize it.",
	"The wise general cuts losses and regroups.",
	"This skirmish may be lost, but the battle may yet be won.",
	"Cornered, trapped and forced to fight on!",
	"True desperation is known only when escape is impossible.",
	"No chance for egress! Will this be a massacre?",
	"Mastery over life and death was chief among my early pursuits. I began in humility, but my ambition was limitless. Who could have divined the prophetic import of something as unremarkable as a twitch in the leg of dead rat?",
	"I entertained a delegation of experts from overseas, eager to plumb the depths of their knowledge and share with them certain techniques and alchemical processes I had found to yield wondrous and terrifying results. Having learned all I could from my visiting guests, I murdered them as they slept.",
	"I brought my colleagues back with much of their intellect intact. A remarkable triumph for even the most experienced necromancer. Freed from the trappings of their humanity, they applied their terrible trade anew. The dead reviving the dead. On and on. Down the years. Forever.",
	"Excavations beneath the manor was well underway, when a particularly ragged indigent arrived in the Hamlet. This filthy, toothless miscreant posted an uncanny knowledge of my ambitions and prognosticated publicly, that, left unchecked, I would soon unleash doom upon the world.",
	"This raving creature had to be silenced, but doing so proved maddeningly impossible. How had he survived the stockades, the icy waters and knives i delivered so enthusiastically into his back? How had he returned, time and time again, to rouse the townsfolk with his wild speculations and prophecies?",
	"Finally, resign to his uncommon corporeal resilience, I lured him to the dig. There, I showed him the thing and detailed the full extent of my plans. Triumphantly, I watched, as he tore his eyes from their sockets and ran shrieking into the shadows, wailing maniacally, that the end was upon us all.",
	"I had collected many rare and elusive volumes on ancient herbal properties and was set to enjoy several weeks immersed in comfortable study. My work was interrupted, however, by a singularly striking young woman, who insisted on repeated calls to the house.",
	"Her knowledge of horticulturism and its role in various arcane practices impressed me greatly. My licentious impulse gave way to a genuine professional respect, and together we began to plant, harvest, and brew.",
	"As time wore on, her wild policy of self-experimentation grew intolerable. She quaffed all manner of strange fungii, herbs and concoctions, intent on gaining some insight into the horror we both knew to be growing beneath us. The change in her was appalling, and, no longer able to stomach it, I sent her to live in the Weald, where her wildness would be welcomed.",
	"Simple folk are by their nature loquacious, and the denizens of the Hamlet were no exception. It was not long before rumors of my morbid genius and secret of excavations began to fuel local legend. In the face of my increasingly egregious flaunting of public taboos, awe turned to ire, and demonstrations were held in the town square",
	"The wild whispers of heresy roused the rabble to violent action. Such was the general air of rebellion, that even my generous offer of gold to the local constabulary was rebuffed. To reassert my rule, I sought out unscrupulous men skilled in the application of force. Tight-lipped and terrifying, these mercenaries brought with them a war machine of terrible implication.",
	"Eager to end the tiresome domestic distraction, I instructed my newly formed militia of hardened bandits, brigands and killers to go forth and do their work. Compliance and order were restored, and annoysome population of the Hamlet was culled to more... Manageable numbers.",
	"The ways and rituals of blood sacrifice are difficult to master. Those from beyond require a physical vessel, if they are to make the crossing into our reality. The timing of the chants is imperative. Without the proper utterances and precise intervals the process can fail spectacularly.",
	"My first attempts at summoning were crude and the results disappointing. I soon found however, that the type and condition of the host's meat was a critical factor. The best results came from pigs, whose flesh is most like that of men.",
	"The great thing I had managed to bring through was brutish and stupid. Moreover, it required prodigious amounts of meat to sustain itself. But this is only a trifling concern. After all, I had a village full of it.",
	"My zeal for blood rituals and summoning rites had begun to ebb, as each attempt invariably brought only failure and disappointment. Progress was halting, and the rapidly accumulating surplus of wasted flesh had become... Burdensome.",
	"I could not store such a prodigious amount of offal, not could I rid myself of it easily, possessed, as it was, by unnamable things from outer spheres. When excavations beneath the manor broke through into an ancient network of aqueducts and tunnels, I knew I had found a solution to the problem of disposal.",
	"The spasmodically squirming, braying and snorting half-corpses were heaped each upon the other until at last I was rid of them. The Warrens had become a landfill of snout and hoof, bristle and bone. A mountainous, twitching mass of misshapen flesh, fusing itself together, in the darkness.",
	"My lofty position wasn't always accompanied by the fear of office, and there was a time, when I could walk the streets or raise a glass at the tavern, without concern for molestation. Faithful, as the tide, one precocious village waif made it her hobby to shadow my every errand. It was charming, then. Troublesome, later.",
	"In financial desperation I've struck a bargain with the ancient things, that surfaced in search of sacrifice, when the moon was right. Their price was the delivery of an obscure idol and one other item of troubling portent. The pact struck, my new found accomplices slipped silently beneath the brackish water. A fearful stirring at the edge of the torchlight betrayed a familiar witness and gifted me with malign inspiration.",
	"Under the blood moon I lured my wide-eyed prey to the pier's edge. Before she could properly appreciate her position I clamped down a manacle, chaining her to the leering idol. A small push was sufficient to send both into the icy waters. And one at length the tide receded, jewels of the most magnificent grandeur lay scattered upon the shore.",
	"Prying eyes had become a nuisance along the Old Road, and so I undertook to receive my most curious deliveries by a way of marine shipments. A sheltered jetty was accessible by a narrow stone stair off the back of the manor, and the discrete system of pulleys could hoist even the heaviest prizes up the rock face from the securely tied dingy below.",
	"I employed a crew of particularly unsavory mariners, who, for a time, sailed the four corners at my behest, retrieving many valuable artifacts, relics and rare texts. Predictably, they increased their tariffs to counter my intense stipulation of secrecy. Such resources had long been exhausted, of course, and so I prepared an alternative payment.",
	"While the greedy dogs slept off their revelry, I hexed their anchor with every twisted incantation I could master, imbuing it with the weight of my ambition and my contempt for their crude extortion. At the witching hour, the anchor pulled with preternatural force, dragging craft and crew down into the depths. They must have cried out, but no sound escaped the swirling black waters...",
	"A Devil walks these halls. Only the mad or the desperate go in search of him.",
	"Towering. Fierce. Terrible. Nightmare made material.",
	"With no living sinew to actuate them, will these walking bones finally fail?",
	"Even the reanimated bones can fell. Even the dead can die again.",
	"There's method in the wild corruption here. It bears a form most wretched and malevolent.",
	"Twisted and maniacal, a slathering testament to the powers of corruption.",
	"Leave her corpse to rot, consumed by the spores she spawned.",
	"The wood is still poisoned, the way is still blocked, but, less people will be eaten.",
	"A nameless abomination, a testament to my failures. It must be destroyed!",
	"It is a travesty. A blundering mountain of hatred and rage.",
	"This thing is even more horrible in death. Liquefaction cannot come soon enough.",
	"How many rats will it take to gnaw through a ton of putrid flesh?",
	"The echoes of his mindless teetering reverberate maddeningly.",
	"The madman hides there, behind the pews, spouting his mindless drivel.",
	"Did he foresee his own demise? I care not, so long as he remains dead.",
	"In life, his claims to precognition were dubious at best, in death, they are ridiculous.",
	"The smell of sulfur and gunpowder hangs in the air. The war machine is close.",
	"A marvel of technology, the engine of destruction!",
	"The corpse of twisted metal and splintered wood... At home amongst the headstones.",
	"The brigands are UNDONE. Our family crest is once again the symbol of strength.",
	"The thing is more terrible, than I can describe. An incoherent jumbled organ, sinew and bone.",
	"Squirming, contorting and ever expanding. This horror must be unmade!",
	"It is as grotesque in death as it was in life...",
	"Its destruction is a small consolation, giving the implications of its terrible existance.",
	"I always wondered what become to the unfortunate little waif.",
	"The aquatic devils remade the poor girl in their image. Now, she is their queen and their slave!",
	"Tedious matriarch! Vile queen of the aquatic depths! She has no place in the sane world!",
	"Seafaring trade, the bloodlife of any port, can resume again, now that the routes are safe.",
	"The poor devils, chained and drowning, for eternity...",
	"Even in death, the captain shouts his orders and his crew obeys!",
	"They are cursed to float forever, deep in the swirling blackness, far beyond the light's reach.",
	"Finally, a sailors' death for captain and crew... Fitting.",
	"Once again, the stars are right, and the Manor sits at the very epicenter of cosmic unrest. Cultists rally to their twisted idols, and great gongs sound in anticipation of the coming sacrifices. Far below, life-laden shadows pulse to the unrelenting rhythm of a beating heart...",
	"The blood of the fallen flows ever downward along these titan spires - the creature fattens itself on your failures...",
	"You have merely glimpsed the edge of the abyss, but it is enough to trigger the cycle of revelation. Now, like me, you will begin to see things as they truly are...",
	"The thing has no name, for it needs no language. Nevertheless, those who would submit to its wordless will thing are rewarded, in a fashion. The creature's blessings are as repulsive as they",
	"are robust. Twisted, half-human monstrosities stalk the flesh-ridden halls, protecting their gestating god.",
	"Madness made flesh! It crawls steadily upward from the pit, supported by the lattice of cyclopean pillars...",
	"The maniacal cultists are quelled for a time, but there can be no celebration. Your progress is measured only in progressive realization, and dawning horror. You are in the shadow of the end.",
	"The interminable stone halls are but an antechamber! The creature is vast beyond measure, and must be battled from within. Step over the threshold and let the terrible truth worm its way into your mind.",
	"The Gateless Gate. A maddening aperture to realms beyond human understanding...",
	"At last, the twisted heart of the world is laid bare – for sword, or supplication.",
	"In all my terrible researches, what I sought was a glimpse behind the veil – a crumb of cosmic truth. I found it here, and in that moment of brain-blasting realization, I ceased to be a man, and became a Herald, an Avatar of the crawling chaos.",
	"Life feeds on life. In your petty pursuit of family redemption, you consume those who rally to your cause, and in so doing, you strengthen the Thing - accelerating the end! This is as it should be...it is why you are here.",
	"We are chained here forever, you and I, at the end of the world. Free yourself, rouse the Thing, and embrace the ineffable cosmic hideousness that lives within us all.",
	"You still foolishly consider yourself an entity separate from the whole. I know better, and I. Will. Show you.",
	"The flesh is fluid – it can be changed, reshaped, remade!",
	"The flesh is immortal, it is undying! Pray it does not take too hideous a form...",
	"Behold the Heart of the World! Progenitor of life, Father and Mother, Alpha and Omega - our creator and our destroyer!",
	"A hollow and ridiculous notion. We are born of this thing, made from it, and we will be returned to it in time.",
	"The great family of man. A profusion of errant flesh. Multiplying, swarming, living, dying.",
	"Until the stars align in their inexorable formation and what sleeps is aroused once more. To hatch from this fragile shell of earth and rock, and bring our inescapable end.",
	"So, seek solace in a manner befitting your lineage, and take up your nugatory vigil, haunted forever by that sickening prose, echoing through the infinite blackness of space and time",
}
